name: default

light:
  colors:
    background: "#ffffff"
    text: "#24292f"
    headings: "#1f2328"
    links: "#0969da"
    code-background: "#f6f8fa"
    border: "#d0d7de"
    blockquote-border: "#d0d7de"
    blockquote-text: "#59636e"
    table-border: "#d0d7de"
    table-row-alt: "#f6f8fa"
    hr: "#d8dee4"
    error-background: "#ffebe9"
    error-border: "#ff8182"
    error-text: "#cf222e"
  font:
    family: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Noto Sans\", Helvetica, Arial, sans-serif"
    mono-family: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace"
    size: "16px"
  highlightjs: github

dark:
  colors:
    background: "#0d1117"
    text: "#e6edf3"
    headings: "#ffffff"
    links: "#58a6ff"
    code-background: "#161b22"
    border: "#30363d"
    blockquote-border: "#3b434b"
    blockquote-text: "#8b949e"
    table-border: "#30363d"
    table-row-alt: "#161b22"
    hr: "#21262d"
    error-background: "#490202"
    error-border: "#f85149"
    error-text: "#f85149"
  font:
    family: "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Noto Sans\", Helvetica, Arial, sans-serif"
    mono-family: "ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace"
    size: "16px"
  highlightjs: github-dark
